# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='pregunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='main.Pregunta'),
        ),
    ]
