# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160311_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pregunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pregunta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
