# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160317_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.datetime(2016, 3, 17, 13, 58, 57, 894005, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.datetime(2016, 3, 17, 13, 58, 57, 893963, tzinfo=utc)),
        ),
    ]
