# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160317_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.date(2016, 3, 17)),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date(2016, 3, 17)),
        ),
    ]
