# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:39
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160317_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, default='')),
                ('logo', models.ImageField(upload_to=b'', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.date(2016, 3, 28)),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date(2016, 3, 28)),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='responsables',
            field=models.ManyToManyField(to='main.Responsable'),
        ),
    ]
