# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160328_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.date(2016, 3, 31)),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date(2016, 3, 31)),
        ),
        migrations.AlterField(
            model_name='eje',
            name='imagen',
            field=models.ImageField(upload_to=b'', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='logo',
            field=models.ImageField(upload_to=b'', verbose_name='Logo'),
        ),
    ]
