# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 22:50
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160331_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.date(2016, 4, 1)),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date(2016, 4, 1)),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=1, help_text='Donde el de orden 0 aparece primero en la lista que  el orden 1'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='La respuesta es una respuesta de hasta 200 caracteres'),
        ),
    ]
