# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160401_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pregunta'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_fin',
            field=models.DateField(default=datetime.date(2016, 4, 6)),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date(2016, 4, 6)),
        ),
    ]
